version: 2.1
# Use code coverage report
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn pwa test --runInBand --coverage
      - run: yarn core-test-ci
      - codecov/upload:
        file: packages/pwa/coverage/*.json
workflows:
  version: 2
  test:
    jobs:
      - test:
        filters:
          branches:
            ignore:
              - gh-pages
